#! /bin/bash
printf '\033[8;40;40t'

cd "$(git config --get wordle.path)"

clear
echo  -e '\033[1m  __    __              _ _      '
echo ' / / /\ \ \___  _ __ __| | | ___ '
echo ' \ \/  \/ / _ \|  __/ _  | |/ _ \'
echo '  \  /\  / (_) | | | (_| | |  __/'
echo -e '   \/  \/ \___/|_|  \__,_|_|\___| \033[0m'

python3 wordle_cli.py

exit
